version: '3'

services:
  tf-serving:
    image: emacski/tensorflow-serving:2.4.1-linux_arm_armv7-a_neon_vfpv4
    volumes:
        - ./src/tf_serving/models/:/models/mobilenet/1/
    ports:
        - 8501:8501 # This might not be necessary, bc container-container communication is done within the network.
    restart: always

  tf-serving-test:
    image: tensorflow-serving-test
    build:
        context: ./tests/tf_serving_test
    volumes:
        - ./logs:/app/logs