version: '3'

services:
  record-cat:
    image: catrecorder:v1
    build:
      context: ./src/record_cat
    volumes:
        - ./data:/app/data
    devices:
        - "/dev/video0:/dev/video0"      
    restart: always

  detect-cat:
    image: catdetector:v1
    build:
      context: ./src/detect_cat
    volumes:
        - ./data:/app/data

  tf-serving:
    image: emacski/tensorflow-serving:2.4.1-linux_arm_armv7-a_neon_vfpv4
    ports:
        - 8501:8501 # This might not be necessary, bc container-container communication is done within the network.
    restart: always

  tf-serving-test:
    image: tensorflow-serving-test
    build:
        context: ./tests/tf_serving_test
    volumes:
        - ./logs:/app/logs

  gcs-sync:
    image: interactwgcs:v1
    build:
      context: ./src/gcs_sync
    volumes:
        - ./data:/app/data
        - ./logs:/app/logs
    restart: always